version: "3"

services:
  client:
    build: ./client
    ports:
      - 8080:8080
    environment:
      - VUE_APP_API_ROOT=http://localhost:5000/api

  server:
    build: ./server
    ports:
      - 5000:5000
  
    environment:
      - NODE_ENV="development"
      - PORT=5000
      - DB_USER=macky
      - DB_PASSWORD=78907890
    
