swagger: "2.0"
info:
  version: "1.1"
  title: "Agent Service - About Component"
host: "localhost:51548"
basePath: "/about"

schemes:
- "http"

paths:
  /:
    get:
      summary: "แสดง AboutBox ของ Agent Service"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/AboutBox"
  /info/:
    get:
      summary: "อ่านข้อมูลของ App, Hardware และ License"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/AppInfo"
  /version/:
    get:
      summary: "อ่านค่า Version ของ Agent Service"
      produces:
      - "application/json"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/AppVersion"

definitions:
  AboutBox:
    type: "object"
    properties:
      appInfo:
        type: "string"
        description: "เลข Version ของ Agent Service"
  AppInfo:
    type: "object"
    properties:
      app:
        type: "object"
        properties:
          version:
            type: "string"
            description: "เลข Version ของ Agent Service"
          component:
            type: "array"
            items:
              type: "string"
              description: "ชื่อ Component ที่มี"
      hardware:
        type: "object"
        properties:
          mainboard:
            type: "object"
            properties:
              serialNo:
                type: "string"
                description: "Serial Number ของ Mainboard"
      license:
        type: "object"
        properties:
          serialNo:
            type: "string"
            description: "Serial Number ของ License"
  AppVersion:
    type: "object"
    properties:
      appVersion:
        type: "string"
        description: "เลข Version ของ Agent Service"
